name: C/C++ CI

on:
  push:
    branches: [ "maintest" ]
  pull_request:
    branches: [ "maintest" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
